[package]
name = "elucid-ingest"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
arrow = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
object_store = { workspace = true, features = ["fs"] }
parquet = { workspace = true, features = ["arrow", "async"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "fs", "rt", "macros"] }
tokio-stream = { workspace = true, features = ["io-util"] }
url = { workspace = true }
uuid = { workspace = true, features = ["v7"] }

[dev-dependencies]
tempfile = { workspace = true }
