[package]
name = "elucid-language"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
ariadne = { workspace = true }
chrono = { workspace = true }
chumsky = { workspace = true, features = ["pratt"] }
elucid-catalog = { workspace = true }
logos = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
uuid = { workspace = true }
