[package]
name = "elucid-metastore"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
elucid-core = { workspace = true }
chrono = { workspace = true }
elucid-catalog = { workspace = true }
elucid-language = { workspace = true }
elucid-storage = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["chrono", "json", "uuid"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
uuid = { workspace = true, features = ["v7"] }

[dev-dependencies]
bytes = { workspace = true }
object_store = { workspace = true, features = ["aws"] }
testcontainers-modules = { workspace = true, features = ["minio", "postgres"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
