[package]
name = "elucid-service"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
axum = { workspace = true, features = ["json", "tokio"] }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
object_store = { workspace = true, features = ["aws"] }
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "net", "rt", "signal", "sync", "time"] }
tokio-util = { workspace = true, features = ["rt"] }
toml_edit = { workspace = true, features = ["parse", "serde"] }
url = { workspace = true }
uuid = { workspace = true, features = ["v7"] }

elucid-catalog = { workspace = true }
elucid-ingestion = { workspace = true }
elucid-metastore = { workspace = true }
elucid-storage = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
testcontainers-modules = { workspace = true, features = ["minio", "postgres"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
uuid = { workspace = true, features = ["v7"] }
