[package]
name = "elucid-engine"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
datafusion = { workspace = true }
object_store = { workspace = true }
url = { workspace = true }

elucid-language = { workspace = true }

[dev-dependencies]
arrow = { workspace = true }
bytes = { workspace = true }
parquet = { workspace = true, features = ["arrow"] }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
