[package]
name = "elucid-engine"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
arrow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
datafusion = { workspace = true }
futures = { workspace = true }
object_store = { workspace = true }
parquet = { workspace = true, features = ["arrow", "object_store"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "time"] }
tokio-util = { workspace = true, features = ["rt"] }

elucid-catalog = { workspace = true }
elucid-language = { workspace = true }
elucid-metastore = { workspace = true }
elucid-storage = { workspace = true }

[dev-dependencies]
bytes = { workspace = true }
sqlx = { workspace = true, features = ["chrono"] }
tempfile = { workspace = true }
testcontainers-modules = { workspace = true, features = ["postgres"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
uuid = { workspace = true }
