[package]
name = "elucid-tests"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
arrow = { workspace = true }
datafusion = { workspace = true }
elucid-catalog = { workspace = true }
elucid-engine = { workspace = true }
elucid-ingestion = { workspace = true }
elucid-language = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "io-util"] }
tempfile = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
bytes = { workspace = true }
futures = { workspace = true }
object_store = { workspace = true, features = ["aws"] }
reqwest = { workspace = true, features = ["rustls-tls"] }
testcontainers-modules = { workspace = true, features = ["localstack"] }
url = { workspace = true }
